package application.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.layout.VBox;

public class OthersController {
	@FXML
	private VBox otherslayout;
	@FXML
	private TextArea skillsTA;
	@FXML
	private TextArea interestsTA;
	@FXML
	private Label warningLabel;
	@FXML
	private Button back;
	@FXML
	private Button cancel;
	@FXML
	private Button generateCV;

	// Event Listener on Button[#back].onAction
	@FXML
	public void othersBackBtnController(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancel].onAction
	@FXML
	public void othersCancelBtnController(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#generateCV].onAction
	@FXML
	public void othersGenerateCvBtnController(ActionEvent event) {
		// TODO Autogenerated
	}
}
