package application.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.layout.VBox;

public class OthersController {
	@FXML
	private VBox otherslayout;
	@FXML
	private TextArea skillsTA;
	@FXML
	private TextArea interestsTA;
	@FXML
	private Label warningLabel;
	@FXML
	private Button back;
	@FXML
	private Button cancel;
	@FXML
	private Button generateCV;

	// Event Listener on Button[#back].onAction
	@FXML
	public void othersBackBtnController(ActionEvent event) throws IOException {
		System.out.println("others back btn pressed");
		VBox pane = FXMLLoader.load(getClass().getResource("../view/Work.fxml"));
		otherslayout.getChildren().setAll(pane);
	}
	// Event Listener on Button[#cancel].onAction
	@FXML
	public void othersCancelBtnController(ActionEvent event) {
		System.out.println("Cancel btn pressed");

		Platform.exit();
		System.exit(0);
	}
	// Event Listener on Button[#generateCV].onAction
	@FXML
	public void othersGenerateCvBtnController(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	public boolean skillsTAFieldValidation() {
		if (skillsTA.getText() == "null" || skillsTA.getText().trim().isEmpty()) {
			warningLabel.setText("*Warning! All of the fields must be filled up");
			System.out.println("False, name null");
			return false;
		}

		else {
			System.out.println(skillsTA.getText());
			System.out.println("True, name not null");
			return true;
		}

	}
	
	
}
