package application.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.layout.VBox;

public class WorkController {
	@FXML
	private VBox worklayout;
	@FXML
	private TextField name1;
	@FXML
	private TextField position1;
	@FXML
	private TextArea description1;
	@FXML
	private TextField name2;
	@FXML
	private TextField position2;
	@FXML
	private TextArea description2;
	@FXML
	private Label warningLabel;
	@FXML
	private Button back;
	@FXML
	private Button cancel;
	@FXML
	private Button next;

	// Event Listener on Button[#back].onAction
	@FXML
	public void workBackBtnActionController(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancel].onAction
	@FXML
	public void workCancelBtnActionController(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#next].onAction
	@FXML
	public void workNextBtnActionController(ActionEvent event) {
		// TODO Autogenerated
	}
}
